//! LLM Backend Abstraction
//!
//! Provides a unified interface for different LLM providers (Claude, Ollama, OpenAI).
//!
//! # Overview
//!
//! The backend trait defines how to decompose complex tasks into subtasks.
//! Each backend implementation handles the API specifics while presenting
//! a common interface to the orchestrator.
//!
//! # Available Backends
//!
//! - `claude`: Anthropic Claude API (recommended)
//! - `ollama`: Local LLM via Ollama
//! - `openai`: OpenAI-compatible APIs (including OpenRouter, vLLM)

pub mod claude;
pub mod ollama;

use std::collections::HashMap;

pub use claude::ClaudeBackend;
pub use ollama::OllamaBackend;

/// A subtask generated by LLM decomposition
#[derive(Debug, Clone)]
pub struct Subtask {
    /// Unique identifier for this subtask
    pub id: usize,

    /// Human-readable description of what to do
    pub description: String,

    /// Dependencies (IDs of subtasks that must complete first)
    pub depends_on: Vec<usize>,

    /// Expected test cases for verification
    pub test_hints: Vec<String>,

    /// Priority (lower = higher priority)
    pub priority: u32,
}

/// Result of task decomposition
#[derive(Debug)]
pub struct DecomposeResult {
    /// List of subtasks to execute
    pub subtasks: Vec<Subtask>,

    /// Overall approach explanation (for debugging/logging)
    pub reasoning: String,

    /// Estimated complexity (1-10)
    pub complexity: u8,
}

/// Trait for LLM backends
///
/// Implementations handle the specifics of each LLM provider while
/// presenting a common interface for task decomposition.
pub trait LlmBackend: Send + Sync {
    /// Get the backend name
    fn name(&self) -> &str;

    /// Check if the backend is available (API key set, service reachable)
    fn is_available(&self) -> bool;

    /// Decompose a complex task into subtasks
    ///
    /// The LLM should break down the task into smaller pieces that
    /// the local model can handle individually.
    fn decompose_task(&self, task: &str, context: &str) -> Result<DecomposeResult, BackendError>;

    /// Get a hint for fixing an error
    ///
    /// When a subtask fails, the LLM can provide guidance on how to fix it.
    fn get_fix_hint(&self, task: &str, error: &str, code: &str) -> Result<String, BackendError>;

    /// Check if the backend supports streaming
    fn supports_streaming(&self) -> bool {
        false
    }
}

/// Backend error types
#[derive(Debug)]
pub enum BackendError {
    /// API key not configured
    NotConfigured { backend: String },

    /// Network/connection error
    NetworkError { message: String },

    /// Rate limit exceeded
    RateLimited { retry_after_secs: Option<u64> },

    /// API returned an error
    ApiError { status: u16, message: String },

    /// Response parsing failed
    ParseError { message: String },

    /// Backend-specific error
    Other { message: String },
}

impl std::fmt::Display for BackendError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            BackendError::NotConfigured { backend } => {
                write!(f, "Backend '{}' not configured (missing API key)", backend)
            }
            BackendError::NetworkError { message } => {
                write!(f, "Network error: {}", message)
            }
            BackendError::RateLimited { retry_after_secs } => {
                if let Some(secs) = retry_after_secs {
                    write!(f, "Rate limited, retry after {} seconds", secs)
                } else {
                    write!(f, "Rate limited")
                }
            }
            BackendError::ApiError { status, message } => {
                write!(f, "API error ({}): {}", status, message)
            }
            BackendError::ParseError { message } => {
                write!(f, "Parse error: {}", message)
            }
            BackendError::Other { message } => {
                write!(f, "Backend error: {}", message)
            }
        }
    }
}

impl std::error::Error for BackendError {}

/// Registry of available LLM backends
pub struct BackendRegistry {
    backends: HashMap<String, Box<dyn LlmBackend>>,
    default: String,
}

impl BackendRegistry {
    /// Create a new registry with default backends
    pub fn new() -> Self {
        let mut registry = Self {
            backends: HashMap::new(),
            default: "claude".to_string(),
        };

        // Register default backends (they may not be configured yet)
        registry.register("claude", Box::new(ClaudeBackend::new()));
        registry.register("ollama", Box::new(OllamaBackend::new()));

        registry
    }

    /// Register a backend
    pub fn register(&mut self, name: &str, backend: Box<dyn LlmBackend>) {
        self.backends.insert(name.to_string(), backend);
    }

    /// Get a backend by name
    pub fn get(&self, name: &str) -> Option<&dyn LlmBackend> {
        self.backends.get(name).map(|b| b.as_ref())
    }

    /// Get the default backend
    pub fn get_default(&self) -> Option<&dyn LlmBackend> {
        self.get(&self.default)
    }

    /// Set the default backend
    pub fn set_default(&mut self, name: &str) -> bool {
        if self.backends.contains_key(name) {
            self.default = name.to_string();
            true
        } else {
            false
        }
    }

    /// List all registered backends
    pub fn list(&self) -> Vec<&str> {
        self.backends.keys().map(|s| s.as_str()).collect()
    }

    /// List available (configured) backends
    pub fn list_available(&self) -> Vec<&str> {
        self.backends
            .iter()
            .filter(|(_, b)| b.is_available())
            .map(|(k, _)| k.as_str())
            .collect()
    }
}

impl Default for BackendRegistry {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_registry_creation() {
        let registry = BackendRegistry::new();
        assert!(registry.list().contains(&"claude"));
        assert!(registry.list().contains(&"ollama"));
    }

    #[test]
    fn test_subtask_creation() {
        let subtask = Subtask {
            id: 1,
            description: "Parse JSON input".to_string(),
            depends_on: vec![],
            test_hints: vec!["should parse {\"key\": 1}".to_string()],
            priority: 1,
        };
        assert_eq!(subtask.id, 1);
        assert!(subtask.depends_on.is_empty());
    }
}
